#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring $app files..."

ynh_restore "$install_dir"
ynh_restore "$data_dir"
ynh_restore "$bbic_etc_dir"
chown -R "root:$app" "$install_dir"
chmod -R go-w "$install_dir"
chown -R root:root "$bbic_etc_dir" "$data_dir"
chmod 0700 "$bbic_etc_dir" "$data_dir"
ynh_config_add --template="bin-wrapper" --destination="$bbic_cli"
chmod 0755 "$bbic_cli"
mkdir -p "$bbic_log_dir"
chown "root:$app" "$bbic_log_dir"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/systemd/system/$app.service"
ynh_restore "/etc/systemd/system/$app-janitor.service"
ynh_restore "/etc/systemd/system/$app.timer"
ynh_restore "/etc/systemd/system/$app-janitor.timer"
ynh_restore "/etc/logrotate.d/$app"
systemctl daemon-reload
bbic_register_service
bbic_apply_schedule
bbic_install_logo

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
